name: build-test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npx lint-staged
      - run: npm run test:coverage
      - run: npm run build
