name: build-test
on:
  push:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup

    - name: Install modules
      run: npm install --silent

    - name: Run Lint
      run: npx lint-staged

    - name: Run unit tests with coverage
      run: |
        SUMMARY="$(npm run test:coverage --coverageReporters=text-summary | tail -3 | head -1)"
        TOKENS=($SUMMARY)
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 9b7d5aa0fe6ff3af0f45f9863f5e86a9
        filename: express-jest-typescript__${{ env.BRANCH }}.json
        label: coverage
        message: ${{ env.COVERAGE }}
        namedLogo: jest
        color: blue
        logoColor: lightblue
